name: sirnawa_mobile
description: "Sirnajaya Kartika Warga"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

flutter_localization:
  sdk: flutter

dependencies:
  cookie_jar: null
  cupertino_icons: ^1.0.8
  lottie:
  dio: null
  dio_cookie_manager: null
  flutter_localization:
  flutter:
    sdk: flutter
  flutter_riverpod: null
  freezed_annotation: null
  go_router: null
  google_fonts: null
  intl: ^0.19.0
  share_plus: ^11.0.0
  json_annotation: ^4.9.0
  logging: null
  lucide_icons: null
  shared_preferences: null
  shimmer: null
  cached_network_image:
  file_picker: null
  flutter_map:
  latlong2:
  flutter_slidable:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  device_info_plus:
  package_info_plus:

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: null

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"
